// this file is generated by auto,please do not modify!!!
package com.fmt.tiktokvideo.nav

import com.fmt.nav_annotation.NavData
import com.fmt.nav_annotation.NavDestination.NavType.Activity
import com.fmt.nav_annotation.NavDestination.NavType.Dialog
import com.fmt.nav_annotation.NavDestination.NavType.Fragment
import com.fmt.nav_annotation.NavDestination.NavType.None
import kotlin.collections.ArrayList
import kotlin.collections.List

public object NavRegistry {
  private val navList: ArrayList<NavData> = ArrayList<NavData>()

  init {
    navList.add(NavData("activity_capture","com.fmt.tiktokvideo.ui.activity.CaptureActivity",false,Activity))
        navList.add(NavData("home_fragment","com.fmt.tiktokvideo.ui.fragment.home.HomeFragment",true,Fragment))
        navList.add(NavData("mine_fragment","com.fmt.tiktokvideo.ui.fragment.mine.MimeFragment",false,Fragment))

  }

  public fun getNavList(): List<NavData> = navList

}
